runtime: nodejs
env: flex
handlers:
- url: /.*
  script: IGNORED
endpoints_api_service:
  name: api.gdgx.io
  config_id: 2017-03-18r0
network:
  instance_tag: https-server
  name: gdg-x
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 300
